apiVersion: v1
kind: Secret
metadata:
  name: mirutinavisual-secrets
type: Opaque
stringData:
  # JWT Secret - Generar uno nuevo para producción
  jwt-secret: "mirutinavisual-production-jwt-secret-2024-very-secure-32chars"
  
  # Session Secret - Generar uno nuevo para producción  
  session-secret: "mirutinavisual-production-session-secret-2024-secure"
  
  # MongoDB Atlas URI - Usar tu URI real
  mongodb-uri: "mongodb+srv://mirutinavisual:5%25S%230mmb@mirutinavisual.1shy5rk.mongodb.net/mirutinavisual?retryWrites=true&w=majority"
  
  # Google OAuth2.0 - Configurar con credenciales reales
  google-client-id: "DEMO_MODE"
  google-client-secret: "DEMO_MODE"
  
---
# ConfigMap para configuraciones no sensibles
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirutinavisual-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  APP_NAME: "MiRutinaVisual Backend"
  APP_VERSION: "1.0.0"
  CORS_ORIGIN: "https://mirutinavisual-frontend.apps.sandbox.x8i5.p1.openshiftapps.com"
